[package]
name = "math_rs"
version = "0.1.0"
authors = ["mkd <monkeydioude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "math_rs"
path = "main.rs"
